-- Vencimentos PA — eventos de notificacao em nuvem
-- Execute este arquivo no Supabase SQL Editor.

create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('BATIDA_FINALIZADA','PIQUE_CONFIRMADO')),
  actor_id uuid references public.profiles(id) on delete set null,
  actor_name text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_activity_events_created_at
  on public.activity_events(created_at desc);

alter table public.activity_events enable row level security;

drop policy if exists "activity_events_select_authenticated" on public.activity_events;
create policy "activity_events_select_authenticated"
on public.activity_events
for select
to authenticated
using (true);

drop policy if exists "activity_events_insert_authenticated" on public.activity_events;
create policy "activity_events_insert_authenticated"
on public.activity_events
for insert
to authenticated
with check (actor_id = auth.uid());

-- Ativa Realtime para os eventos.
-- Se o Supabase informar que a tabela ja esta na publication,
-- nao e necessario repetir esta linha.
alter publication supabase_realtime add table public.activity_events;
