-- Projeto Vencimento PA V3.19 — eventos em tempo real para notificações
create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  tipo text not null,
  actor_id uuid not null references auth.users(id) on delete cascade,
  actor_name text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.activity_events enable row level security;

drop policy if exists "activity_events_select_authenticated" on public.activity_events;
create policy "activity_events_select_authenticated"
on public.activity_events for select to authenticated
using (true);

drop policy if exists "activity_events_insert_authenticated" on public.activity_events;
create policy "activity_events_insert_authenticated"
on public.activity_events for insert to authenticated
with check (actor_id = auth.uid());

grant select, insert on public.activity_events to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.activity_events;
exception when duplicate_object then
  null;
end $$;
